name: django-serve-spa
version: 0.1.0-rc0
description: Serve SPAs with Django

repo_url: https://github.com/kaoslabsinc/django-serve-spa
project_url: https://github.com/kaoslabsinc/django-serve-spa
keywords: django, spa, react, serve
